
using DemogRPC.Protos;
using Grpc.Core;

namespace DemogRPC.Services;
//1. right click on the proto file and select the protobuf compiler 
//2. select what type of implementation we want to generate Server or client or both
//create a class that inherits from the autogenerated grpc protofile
// Use all asp.net features inside the class as needed. ex logging, DI etc.
public class DemoMessageService : DemoGrpcService.DemoGrpcServiceBase
{
    private readonly ILogger logger;

    public DemoMessageService(ILoggerFactory loggerFactory)
     => logger = loggerFactory.CreateLogger(nameof(DemoMessageService));

    //override the implementation in the base class and use any c# constructs as needed.
    public override Task<HelloResponse> demomessage(HelloRequest request, ServerCallContext context)
      => Task.FromResult(new HelloResponse { Name = request.Name, Iteration = new Random().Next(1, 1000) });



}
